# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d506a16f17724af9b353dcaac894716e5e4f75da340b5bc2481853a37a4282ab60f9cc79abecc52d548a5cd9760522cfb0e4640d1559ad913fb753d345c2fb1

test:
  secret_key_base: 9b853663cfa230c2e1895f288fe667fb7656332e2f4828cd11362fbcf28e4a7fd2696b6bd9cd2cb1a3d3b8eb974ad5aa3b58d2af44e3815732a209ca2642d3c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
